version: '3.5'

services:
  gatewayql:
  # image is provided by docker build of local app using Dockerfile
    container_name: gatewayql
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      labels: 
        - "gatewayql"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/dist
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229 # FOR DEBUG
    command: npm run start:debug
    env_file: .env
    networks:
      - gatewayql
    links: 
      - postgres
    depends_on:
      - postgres
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    container_name: gatewayql_postgres
    env_file: .env
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gatewayql
      - PGDATA=/data/postgres
    image: postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - gatewayql
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: gatewayql_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - gatewayql
    restart: unless-stopped
    depends_on: 
      - postgres

networks:
  gatewayql:
  
volumes:
  postgres:
  pgadmin:
